# ???
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: test123
  mvc:
    static-path-pattern: /static/**
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
#    view:
#      prefix: /WEB-INF/page/
#      suffix: .jsp
logging:
  config: classpath:logback-spring.xml
# mybatis-plus ??
mybatis-plus:
  # xml??
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      # ????
      # table-prefix: tb_
      #???? AUTO: ??????ID INPUT:"??id",ID_WORKER:"??id????", UUID:"??UUID????";
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    # ??????? ???????
    map-underscore-to-camel-case: false
    # ???setter?????
    call-setters-on-nulls: true
    # sql??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl