package cn.huaxiaerp.huaxia_erp.datasource.mappers;

import cn.huaxiaerp.huaxia_erp.datasource.po.OrgaUserRel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrgaUserRelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbggenerated
     */
    int insert(OrgaUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbggenerated
     */
    int insertSelective(OrgaUserRel record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbggenerated
     */
    OrgaUserRel selectByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgaUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgaUserRel record);
}